config/routes.rb
StatisticallySpeaking::Application.routes.draw do
  resources :players

  resources :teams
  
  resources :blocks

  resources :away_scores

  resources :home_scores

  resources :games do
	  member do
		get 'update_score'
	  end
	end

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  get "static_pages/home"
  
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
  

  root 'games#index'

  

end

app/models/home_score.rb
class HomeScore < ActiveRecord::Base
	has_many :blocks
end

app/controllers/home_scores_controller.rb
class HomeScoresController < ApplicationController
  before_action :set_home_score, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user

  # GET /home_scores
  # GET /home_scores.json
  def index
    @home_scores = HomeScore.all
  end

  # GET /home_scores/1
  # GET /home_scores/1.json
  def show
  end

  # GET /home_scores/new
  def new
    @home_score = HomeScore.new
  end

  # GET /home_scores/1/edit
  def edit
  end

  # POST /home_scores
  # POST /home_scores.json
  def create
    @home_score = HomeScore.new(home_score_params)

    respond_to do |format|
      if @home_score.save
        format.html { redirect_to @home_score, notice: 'Home score was successfully created.' }
        format.json { render action: 'show', status: :created, location: @home_score }
      else
        format.html { render action: 'new' }
        format.json { render json: @home_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /home_scores/1
  # PATCH/PUT /home_scores/1.json
  def update
    respond_to do |format|
      if @home_score.update(home_score_params)
        format.html { redirect_to @home_score, notice: 'Home score was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @home_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /home_scores/1
  # DELETE /home_scores/1.json
  def destroy
    @home_score.destroy
    respond_to do |format|
      format.html { redirect_to home_scores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home_score
      @home_score = HomeScore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_score_params
      params.require(:home_score).permit(:ones, :display_order)
    end
end

app/helpers/home_scores_helper.rb
module HomeScoresHelper
end

app/views/home_scores/_form.html.erb
<%= form_for(@home_score) do |f| %>
  <% if @home_score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home_score.errors.count, "error") %> prohibited this home_score from being saved:</h2>

      <ul>
      <% @home_score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ones %><br>
    <%= f.number_field :ones %>
  </div>
  <div class="field">
    <%= f.label :display_order %><br>
    <%= f.number_field :display_order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/home_scores/edit.html.erb
<h1>Editing home_score</h1>

<%= render 'form' %>

<%= link_to 'Show', @home_score %> |
<%= link_to 'Back', home_scores_path %>

app/views/home_scores/index.html.erb
<h1>Listing home_scores</h1>

<table>
  <thead>
    <tr>
      <th>Ones</th>
      <th>Display order</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @home_scores.each do |home_score| %>
      <tr>
        <td><%= home_score.ones %></td>
        <td><%= home_score.display_order %></td>
        <td><%= link_to 'Show', home_score %></td>
        <td><%= link_to 'Edit', edit_home_score_path(home_score) %></td>
        <td><%= link_to 'Destroy', home_score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Home score', new_home_score_path %>

app/views/home_scores/new.html.erb
<h1>New home_score</h1>

<%= render 'form' %>

<%= link_to 'Back', home_scores_path %>

app/views/home_scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ones:</strong>
  <%= @home_score.ones %>
</p>

<p>
  <strong>Display order:</strong>
  <%= @home_score.display_order %>
</p>

<%= link_to 'Edit', edit_home_score_path(@home_score) %> |
<%= link_to 'Back', home_scores_path %>