config/routes.rb
StatisticallySpeaking::Application.routes.draw do
  resources :players

  resources :teams
  
  resources :blocks

  resources :away_scores

  resources :home_scores

  resources :games do
	  member do
		get 'update_score'
	  end
	end

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  get "static_pages/home"
  
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
  

  root 'games#index'

  

end

app/models/away_score.rb
class AwayScore < ActiveRecord::Base
	has_many :blocks
end

app/controllers/away_scores_controller.rb
class AwayScoresController < ApplicationController
  before_action :set_away_score, only: [:show, :edit, :update, :destroy]
  	before_action :signed_in_user

  # GET /away_scores
  # GET /away_scores.json
  def index
    @away_scores = AwayScore.all
  end

  # GET /away_scores/1
  # GET /away_scores/1.json
  def show
  end

  # GET /away_scores/new
  def new
    @away_score = AwayScore.new
  end

  # GET /away_scores/1/edit
  def edit
  end

  # POST /away_scores
  # POST /away_scores.json
  def create
    @away_score = AwayScore.new(away_score_params)

    respond_to do |format|
      if @away_score.save
        format.html { redirect_to @away_score, notice: 'Away score was successfully created.' }
        format.json { render action: 'show', status: :created, location: @away_score }
      else
        format.html { render action: 'new' }
        format.json { render json: @away_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /away_scores/1
  # PATCH/PUT /away_scores/1.json
  def update
    respond_to do |format|
      if @away_score.update(away_score_params)
        format.html { redirect_to @away_score, notice: 'Away score was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @away_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /away_scores/1
  # DELETE /away_scores/1.json
  def destroy
    @away_score.destroy
    respond_to do |format|
      format.html { redirect_to away_scores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_away_score
      @away_score = AwayScore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def away_score_params
      params.require(:away_score).permit(:ones, :display_order)
    end
end

app/helpers/away_scores_helper.rb
module AwayScoresHelper
end

app/views/away_scores/_form.html.erb
<%= form_for(@away_score) do |f| %>
  <% if @away_score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@away_score.errors.count, "error") %> prohibited this away_score from being saved:</h2>

      <ul>
      <% @away_score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ones %><br>
    <%= f.number_field :ones %>
  </div>
  <div class="field">
    <%= f.label :display_order %><br>
    <%= f.number_field :display_order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/away_scores/edit.html.erb
<h1>Editing away_score</h1>

<%= render 'form' %>

<%= link_to 'Show', @away_score %> |
<%= link_to 'Back', away_scores_path %>

app/views/away_scores/index.html.erb
<h1>Listing away_scores</h1>

<table>
  <thead>
    <tr>
      <th>Ones</th>
      <th>Display order</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @away_scores.each do |away_score| %>
      <tr>
        <td><%= away_score.ones %></td>
        <td><%= away_score.display_order %></td>
        <td><%= link_to 'Show', away_score %></td>
        <td><%= link_to 'Edit', edit_away_score_path(away_score) %></td>
        <td><%= link_to 'Destroy', away_score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Away score', new_away_score_path %>

app/views/away_scores/new.html.erb
<h1>New away_score</h1>

<%= render 'form' %>

<%= link_to 'Back', away_scores_path %>

app/views/away_scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ones:</strong>
  <%= @away_score.ones %>
</p>

<p>
  <strong>Display order:</strong>
  <%= @away_score.display_order %>
</p>

<%= link_to 'Edit', edit_away_score_path(@away_score) %> |
<%= link_to 'Back', away_scores_path %>