config/routes.rb
StatisticallySpeaking::Application.routes.draw do
  resources :players

  resources :teams
  
  resources :blocks

  resources :away_scores

  resources :home_scores

  resources :games do
	  member do
		get 'update_score'
	  end
	end

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  get "static_pages/home"
  
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
  

  root 'games#index'

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <span>March Madness</span>
    2014
  </small>
</footer>

app/views/layouts/_header.html.erb
    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">bracketology</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
			  <li><%= link_to "Blocks", blocks_path %></li>
			  <li><%= link_to "Games", games_path %></li>
			  <li><%= link_to "Players", players_path %></li>
			  <li><%= link_to "Teams", teams_path %></li>
			  <% if signed_in? %>
			    <li><%= link_to "Users", users_path %></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><%= link_to "Profile", edit_user_path(current_user) %></li>
						<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
					</ul>
				</li>
			  <% else %>
			    <li><%= link_to "Sign in", signin_path %></li>
			  <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>March Madness</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
	
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-34175205-2', 'bracketologypool.herokuapp.com');
	  ga('send', 'pageview');

	</script>

  </head>
  <body>
    <%= render 'layouts/header' %>
    <div id="main-container" class="container">
	  <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
	  <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>